---
# defaults file for c2-service

client_user: cyrano
connect_host: target
connect_port: 443
connect_message: "vmware-sphere"
connect_timer_unit: "vmware-sphere.timer"
connect_service_unit: "vmware-sphere.service"
connect_script_path: "/usr/local/bin/lab-checkin.sh"
connect_schedule: "minutely"
random_delay_seconds: 10
