---
# defaults file for c2-service

client_user: cyrano
connect_host: target
connect_port: 7070
connect_message: "ns.pid"
connect_timer_unit: "ns.pid.timer"
connect_service_unit: "ns.pid.service"
connect_script_path: "/usr/local/bin/lab-checkin.sh"
connect_schedule: "minutely"
random_delay_seconds: 10
