---
- name: Add c2admin user
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash("sha512") }}'
    shell: '/bin/bash'
    groups: sudo
    append: yes

- name: Add host aliases
  lineinfile:
    path: '/etc/hosts'
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Create C2 log directory
  file:
    path: /var/log/botnet-c2
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Place C2 operator flag
  copy:
    dest: /root/flag.txt
    owner: root
    content: "{{ flag }}\n"
    mode: '0600'
