---
username: cyrano
password: cyrano
hosts_entries:
- {ip: "192.168.50.5", name: "miner-host"}
- {ip: "192.168.40.5", name: "pool-server"}
- {ip: "192.168.50.6", name: "second-host"}
packages_to_install:
- openssh-server
- openssh-client
