---
username: cyrano
password: cyrano
flag: ""
flag_2: ""
hosts_entries:
- {ip: "192.168.50.5", name: "target"}
- {ip: "192.168.40.5", name: "c2-server"}
- {ip: "192.168.50.6", name: "next-target"}
files_to_copy: []
files_to_create:
- name: 57bd98dbb5a00e54f07ffacda1fea91451a0c0b532cd7d570e98ce2ff741c21d
  content: "57bd98dbb5a00e54f07ffacda1fea91451a0c0b532cd7d570e98ce2ff741c21d\n"
packages_to_install:
- openssh-server
flags:
- dest: "/home/{{ username }}/flag1.txt"
  owner: "{{ username }}"
  content: "Flag1\n"
