---
- name: Add host aliases
  lineinfile:
    path: '/etc/hosts'
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop: "{{ hosts_entries }}"

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash("sha512") }}'
    shell: '/bin/bash'
    groups: sudo
    append: yes
    state: present

- name: Install packages
  apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: yes

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

